{{- if eq .Values.k8sPermissionsType "NAMESPACE_ADMIN" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-harness-namespace-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}

{{- if eq .Values.k8sPermissionsType "CI_USER" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}-harness-ci-user
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
{{- end }}