{{- if not .Values.existingDelegateToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harness-delegate-ng.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "harness-delegate-ng.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Base 64 encoded account secret
  DELEGATE_TOKEN: {{ .Values.delegateToken | b64enc | quote }}
{{- end }}
