apiVersion: v1
kind: Service
metadata:
  name: {{ include "harness-delegate-ng.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "harness-delegate-ng.selectorLabels" . | nindent 4 }}
