{{- if .Values.upgrader.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
  name: {{ template "harness-delegate-ng.fullname" . }}-upgrader-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ template "harness-delegate-ng.fullname" . }}-{{ .Values.upgrader.cronJobServiceAccountName }}
          restartPolicy: Never
          securityContext:
            fsGroup: 1001
          containers:
            - image: {{ .Values.upgrader.upgraderDockerImage }}
              name: upgrader
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: {{ include "harness-delegate-ng.upgraderDelegateToken" . }}
              volumeMounts:
              {{- if $.Values.upgraderCustomCa.secretName }}
                - name: custom-certs
                  mountPath: /ca-bundle
                  readOnly: true
              {{- end }}
                - name: config-volume
                  mountPath: /etc/config
          volumes:
          {{- if $.Values.upgraderCustomCa.secretName }}
            - name: custom-certs
              secret:
                secretName: {{ .Values.upgraderCustomCa.secretName }}
                defaultMode: 400
          {{- end }}
            - name: config-volume
              configMap:
                name: {{ .Values.delegateName }}-upgrader-config
{{- end }}
